services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        env_file: .env
        environment:
            - DB_HOST=db
            - REDIS_HOST=redis
        depends_on:
            - db
            - redis
        networks:
            - strathport-network

    db:
        image: postgres:16
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - strathport-network

    redis:
        image: redis:alpine
        volumes:
            - redis_data:/data
        ports:
            - "6379:6379"
        networks:
            - strathport-network

networks:
    strathport-network:
        driver: bridge

volumes:
    postgres_data:
    redis_data:
